# Generated by Django 4.1.5 on 2023-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todoitem_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.AddField(
            model_name='device',
            name='email',
            field=models.EmailField(default=None, max_length=200),
        ),
    ]
