# Generated by Django 4.1.5 on 2023-04-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_device_device_id_device_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='TodoUsers',
        ),
    ]
