# Generated by Django 4.1.5 on 2023-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_todousers_todoitem_user_alter_todoitem_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='item_id',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
