# Generated by Django 4.1.5 on 2023-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_todoitem_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
