# Generated by Django 4.1.5 on 2023-04-08 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0008_remove_todoitem_mail_remove_todoitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='mail',
            field=models.EmailField(default='mail', max_length=254),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
