# Generated by Django 4.1.5 on 2023-04-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_todoitem_mail_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
