# Generated by Django 4.1.5 on 2023-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_remove_todoitem_mail_remove_todoitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='mail',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='password',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
